parameters:
    
    
services:
    targetprocess:
        class: ZENben\Bundle\TargetProcessBundle\Service\TargetProcessService
        arguments:
            - '@buzz'
            - '@security.context'
            - %targetprocess%